"""OutfitCheck AI - SQLAlchemy Models"""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, DateTime, Boolean, Float, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from backend.database import Base


def generate_uuid():
    return str(uuid.uuid4())


class User(Base):
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=generate_uuid)
    email = Column(String, unique=True, nullable=False, index=True)
    username = Column(String, unique=True, nullable=False, index=True)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String, default="")
    style_preferences = Column(JSON, default=dict)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    garments = relationship("Garment", back_populates="owner", cascade="all, delete-orphan")
    outfits = relationship("Outfit", back_populates="owner", cascade="all, delete-orphan")


class Garment(Base):
    __tablename__ = "garments"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    name = Column(String, nullable=False)
    category = Column(String, nullable=False)  # top, bottom, shoes, accessory, outerwear, dress
    subcategory = Column(String, default="")  # t-shirt, jeans, sneakers, etc.
    color = Column(String, default="")
    season = Column(String, default="all")  # spring, summer, autumn, winter, all
    occasion = Column(String, default="casual")  # casual, formal, sport, party, work
    image_url = Column(String, default="")
    description = Column(Text, default="")
    ai_tags = Column(JSON, default=list)  # Tags generated by Gemini Vision
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    owner = relationship("User", back_populates="garments")


class Outfit(Base):
    __tablename__ = "outfits"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    name = Column(String, default="")
    garment_ids = Column(JSON, default=list)  # List of garment IDs
    occasion = Column(String, default="casual")
    weather_context = Column(String, default="")
    is_favorite = Column(Boolean, default=False)
    ai_score = Column(Float, default=0.0)
    ai_feedback = Column(JSON, default=dict)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    owner = relationship("User", back_populates="outfits")


class AIFeedbackHistory(Base):
    __tablename__ = "ai_feedback_history"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    outfit_id = Column(String, ForeignKey("outfits.id"), nullable=True)
    agent_type = Column(String, nullable=False)  # "outfit_stylist" or "fashion_critic"
    input_data = Column(JSON, default=dict)
    output_data = Column(JSON, default=dict)
    created_at = Column(DateTime, default=datetime.utcnow)
